name: MacOS CI

permissions:
  contents: read

on:
  pull_request:
jobs:
  ci-macfuse:
    runs-on: macos-26
    env:
      PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
    steps:
      - uses: actions/checkout@v4

      - name: Cache
        id: rust-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.rustup/toolchains/
            target/
          key: ${{ runner.os }}-cargo-compile-v1-${{ hashFiles('**/Cargo.toml', '.github/workflows/*.yml') }}

      - name: Install packages
        run: |
          brew update > /dev/null && brew install autoconf automake
          brew install --cask macfuse

      - name: Install Rust
        run: |
          rustc --version
          cargo --version

      - name: Build all targets
        run: cargo build --all --all-targets

      - name: Build all targets, all features
        run: cargo build --all --all-targets --all-features

      - name: Run cargo doc for all features
        run: cargo doc --all --no-deps --all-features
