name: MacStadium CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  macfuse:
    runs-on: macstadium
    environment: macstadium   # approval gate for security
    env:
      PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/macfuse-ci
